import { version } from "@zpk";

export type InitialDataType = typeof InitialData;
export type Key = keyof InitialDataType;
export type Value = InitialDataType[Key];

export const InitialData = {
    toggleZPKMod: false,
    landtolbx: 0,
    landtolbz: 0,
    landx: 0,
    landy: 0,
    landz: 0,
    hitx: 0,
    hity: 0,
    hitz: 0,
    lbon: false,
    os: Infinity,
    osx: Infinity,
    osz: Infinity,
    sqos: Infinity,
    pb: Infinity,
    pbx: Infinity,
    pbz: Infinity,
    tier: 0,
    lb: { x: 0, y: 0, z: 0 },
    ja: 0,
    hita: 0,
    pTF: 6,
    rTF: 4,
    tc1: "d",
    tc2: "f",
    separateGui: true,
    idx: 1,
    showpos: true,
    showfac: true,
    showpit: true,
    showja: true,
    showhita: true,
    showspeed: true,
    showttspeed: true,
    showtier: true,
    showland: true,
    showhit: true,
    showos: true,
    showpb: true,
    showLastTurning: true,
    showLastTiming: true,
    prefix: "<ZPK> ",
    customText: `§l§o§7ZPK Mod (${version})`,
    sendpb: true,
    sendpbx: true,
    sendpbz: true,
    sendosz: false,
    sendosx: false,
    sendos: false,
    befLand: false,
    befWalk: false,
    befJump: false,
    befLandLB: false,
    befSprinting: false,
    befTFac: 0,
    lastTurning: 0,
    lastTiming: "N/A",
    jumpTick: 0,
    walkTick: 0,
    sprintTick: 0,
    lastTimingTick: 0,
    jam: false,
    HH: false,
    sprint: false,
    pessi: false,
};
