export const zpkModOn = true;
export const cmdPrefix = '.';
export const version = '6.0.0';

export const InitialData = {
  toggleZPKMod: true,
  landtolbx: 0,
  landtolbz: 0,
  landx: 0,
  landy: 0,
  landz: 0,
  hitx: 0,
  hity: 0,
  hitz: 0,
  lbon: false,
  os: Infinity,
  osx: Infinity,
  osz: Infinity,
  sqos: Infinity,
  pb: Infinity,
  pbx: Infinity,
  pbz: Infinity,
  tier: 0,
  lbx: 0,
  lby: 0,
  lbz: 0,
  ja: 0,
  hita: 0,
  pTF: 6,
  rTF: 4,
  tc1: 'd',
  tc2: 'f',
  separateGui: true,
  idx: 1,
  showpos: true,
  showfac: true,
  showpit: true,
  showja: true,
  showhita: true,
  showspeed: true,
  showttspeed: true,
  showtier: true,
  showland: true,
  showhit: true,
  showos: true,
  showpb: true,
  showturn: true,
  prefix: '<ZPK> ',
  customText: `§l§o§7ZPK Mod (${version})`,
  sendpb: true,
  sendpbx: true,
  sendpbz: true,
  sendosz: false,
  sendosx: false,
  sendos: false,
  beforetland: false,
  beforelandlb: false,
  beforetfac: 0,
  lastturning: 0,
};
